# -*- coding: utf-8 -*-

from sklearn.datasets import make_classification, make_regression
from .datasets import SimpleDataset


class SKLearnSyntheticClassification(SimpleDataset):
    """Dataset generated by sklearn's make_classification function."""

    def __init__(self, *args, **kwargs) -> None:
        """Create an SKLearnSyntheticClassification object.

        Args:

            *args:    Variable length argument list to be passed to
                      make_classification().
            **kwargs: Arbitrary keyword arguments to be passed to
                      make_classification().

        """
        inputs, targets = make_classification(*args, **kwargs)
        super().__init__(inputs, targets)


class SKLearnSyntheticRegression(SimpleDataset):
    """Dataset generated by sklearn's make_regression function."""

    def __init__(self, *args, **kwargs) -> None:
        """Create an SKLearnSyntheticRegression object.

        Args:

            *args:    Variable length argument list to be passed to
                      make_regression().
            **kwargs: Arbitrary keyword arguments to be passed to
                      make_regression().

        """
        inputs, targets = make_regression(*args, **kwargs)
        super().__init__(inputs, targets)
